platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: pal-stocks

outputs:
- name: package-output

run:
  path: pal-stocks/ci/tasks/package.sh